# config file version
apiVersion: 1

datasources:    
  - name: BGP Failover Metrics
    type: elasticsearch
    access: proxy
    url: http://172.90.90.9:9200
    isDefault: false
    jsonData:
      index: '[bgp-failover-]YYYY.MM.DD'
      interval: Daily
      timeField: '@timestamp'
      logMessageField: change_reason
