# config file version
apiVersion: 1

datasources:    
    
  # Nuevo data source - BGP Failover Metrics
  - name: BGP Failover Metrics
    type: elasticsearch
    access: proxy
    url: http://172.90.90.9:9200  # Cambiar si Elasticsearch está en otra IP
    isDefault: true  # Hacer este el data source por defecto
    jsonData:
      index: 'bgp-failover-metrics'  # Índice sin patrón de fecha
      interval: None
      timeField: '@timestamp'
      #esVersion: '8.0.0'  # Ajustar según tu versión de Elasticsearch
      timeInterval: '30s'
      logMessageField: change_reason
      logLevelField: ''
    editable: true
